import { useState } from 'react'
import type { FormEvent } from 'react'
import { MapPin } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '@/context/AuthContext'
import { useProjects } from '@/context/ProjectsContext'
import { TopNav } from '@/components/TopNav'
import '@/App.css'
export function CreateProjectPage() { const { user } = useAuth(); const { addProject } = useProjects(); const navigate = useNavigate(); const [title,setTitle] = useState(''); const [location,setLocation] = useState(''); const [startDate,setStartDate] = useState(''); const [endDate,setEndDate] = useState(''); const [description,setDescription] = useState(''); const [coordinates,setCoordinates] = useState('21.1458, 79.0882'); if (!user) return null; const department = user.department; function submit(event: FormEvent) { event.preventDefault(); addProject({ title, location: `${location} (${coordinates})`, startDate, endDate, description, department }); navigate('/projects') } return <main className="app-page"><TopNav/><section className="page-content form-page"><p className="eyebrow">{department.toUpperCase()} DEPARTMENT</p><h1>Create upcoming project</h1><p className="page-intro">Add work to the coordination pipeline before excavation is scheduled.</p><form className="project-form" onSubmit={submit}><label>Project title<input required value={title} onChange={event=>setTitle(event.target.value)} placeholder="e.g. Central Avenue pipeline renewal"/></label><label>Work location<input required value={location} onChange={event=>setLocation(event.target.value)} placeholder="e.g. Central Avenue, Ward 32"/></label><label className="location-picker">Selected map location<div><MapPin size={17}/><input required value={coordinates} onChange={event=>setCoordinates(event.target.value)} placeholder="Latitude, Longitude"/></div><small>Enter coordinates from the map location. Interactive map selection can use this same field later.</small></label><div className="date-fields"><label>Start date<input required value={startDate} onChange={event=>setStartDate(event.target.value)} type="date"/></label><label>End date<input required value={endDate} onChange={event=>setEndDate(event.target.value)} type="date"/></label></div><label>Work description<textarea required value={description} onChange={event=>setDescription(event.target.value)} placeholder="Describe the proposed work and excavation needs." rows={4}/></label><button className="submit-project">Create project</button></form></section></main> }
