import { useEffect, useState } from "react";
import { Bell } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { API_BASE, authHeaders } from "@/context/AuthContext";
import { TopNav } from "@/components/TopNav";
import "@/App.css";

type Notice = {
  id: string;
  title: string;
  message: string;
  created_at: string;
  read_at: string | null;
  proposal_id: string | null;
  project_id: string | null;
};

export function NotificationsPage() {
  const navigate = useNavigate();
  const [notices, setNotices] = useState<Notice[]>([]);

  useEffect(() => {
    fetch(`${API_BASE}/notifications`, { headers: authHeaders() })
      .then((r) => r.json())
      .then((data) => {
        setNotices(data);
        // Automatically mark all unread notifications as read on opening the notifications page
        fetch(`${API_BASE}/notifications/read-all`, {
          method: "POST",
          headers: authHeaders(),
        })
          .then(() => {
            window.dispatchEvent(new Event("notificationsRead"));
          })
          .catch(() => {});
      })
      .catch(() => setNotices([]));
  }, []);

  function markReadAndNavigate(notice: Notice, to: string) {
    // Mark notification as read (fire-and-forget) then navigate
    fetch(`${API_BASE}/notifications/${notice.id}/read`, {
      method: "POST",
      headers: authHeaders(),
    })
      .then(() => {
        window.dispatchEvent(new Event("notificationsRead"));
      })
      .catch(() => {});
    navigate(to);
  }

  return (
    <main className="app-page">
      <TopNav />
      <section className="page-content">
        <p className="eyebrow">ACTION CENTRE</p>
        <h1>Notifications</h1>
        <p className="page-intro">
          Workflow events generated by projects and coordination responses.
        </p>
        <div className="notification-list">
          {notices.length ? (
            notices.map((notice) => (
              <article className="notification-card" key={notice.id}>
                <span className={`notice-icon ${notice.read_at ? "info" : "urgent"}`}>
                  <Bell size={18} />
                </span>
                <div>
                  <div className="notice-heading">
                    <h3>{notice.title}</h3>
                    <small>{new Date(notice.created_at).toLocaleString()}</small>
                  </div>
                  <p>{notice.message}</p>
                  <div className="notice-actions">
                    {notice.project_id && (
                      <button
                        className="text-button"
                        onClick={() => markReadAndNavigate(notice, `/projects/${notice.project_id}`)}
                      >
                        View project →
                      </button>
                    )}
                    {notice.proposal_id && (
                      <Link className="text-button" to={`/coordination/proposals/${notice.proposal_id}`}>
                        Review proposal →
                      </Link>
                    )}
                  </div>
                </div>
              </article>
            ))
          ) : (
            <div className="empty-state">No workflow notifications yet.</div>
          )}
        </div>
      </section>
    </main>
  );
}
